spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql : true
    hibernate.ddl-auto: none

jwt:
  issuer: UNITECH_BACKEND_MS_SECURITY_AUTHENTICATION
  alias: for-jwt
  expirationTime:
    token:
      accessInMinutes: 1
      refreshInMonths: 3